
// PureMark Copyright 2025. All rights reserved.
// Distributed under the AGPLv3+ license. See LICENSE file for details.
//
// This file is autogenerated based on the C file:
// C:\Users\lucas\dev\crossplatform\test\puremark\src\pmrender\src\bindings.h
// Do not modify manually. Any modifications to the original C file will
// require regeneration of this file.

        
import 'dart:ffi';
import 'package:ffi/ffi.dart' as adv; // For Pointer and Dynamic memory allocation.
final dylib = DynamicLibrary.open('lib/autogen/native_libraries/windows/fmrender.dll');

